/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as ReconcilerRouteImport } from './routes/reconciler'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LeasesRouteImport } from './routes/leases'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconcilerRoute = ReconcilerRouteImport.update({
  id: '/reconciler',
  path: '/reconciler',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasesRoute = LeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/leases': typeof LeasesRoute
  '/memory': typeof MemoryRoute
  '/pipelines': typeof PipelinesRoute
  '/planner': typeof PlannerRoute
  '/reconciler': typeof ReconcilerRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/leases': typeof LeasesRoute
  '/memory': typeof MemoryRoute
  '/pipelines': typeof PipelinesRoute
  '/planner': typeof PlannerRoute
  '/reconciler': typeof ReconcilerRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/deployments': typeof DeploymentsRoute
  '/knowledge': typeof KnowledgeRoute
  '/leases': typeof LeasesRoute
  '/memory': typeof MemoryRoute
  '/pipelines': typeof PipelinesRoute
  '/planner': typeof PlannerRoute
  '/reconciler': typeof ReconcilerRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/deployments'
    | '/knowledge'
    | '/leases'
    | '/memory'
    | '/pipelines'
    | '/planner'
    | '/reconciler'
    | '/runtime'
    | '/settings'
    | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/deployments'
    | '/knowledge'
    | '/leases'
    | '/memory'
    | '/pipelines'
    | '/planner'
    | '/reconciler'
    | '/runtime'
    | '/settings'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/billing'
    | '/dashboard'
    | '/deployments'
    | '/knowledge'
    | '/leases'
    | '/memory'
    | '/pipelines'
    | '/planner'
    | '/reconciler'
    | '/runtime'
    | '/settings'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  DeploymentsRoute: typeof DeploymentsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LeasesRoute: typeof LeasesRoute
  MemoryRoute: typeof MemoryRoute
  PipelinesRoute: typeof PipelinesRoute
  PlannerRoute: typeof PlannerRoute
  ReconcilerRoute: typeof ReconcilerRoute
  RuntimeRoute: typeof RuntimeRoute
  SettingsRoute: typeof SettingsRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciler': {
      id: '/reconciler'
      path: '/reconciler'
      fullPath: '/reconciler'
      preLoaderRoute: typeof ReconcilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leases': {
      id: '/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof LeasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  DeploymentsRoute: DeploymentsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LeasesRoute: LeasesRoute,
  MemoryRoute: MemoryRoute,
  PipelinesRoute: PipelinesRoute,
  PlannerRoute: PlannerRoute,
  ReconcilerRoute: ReconcilerRoute,
  RuntimeRoute: RuntimeRoute,
  SettingsRoute: SettingsRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
